---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1u2anh7rm26qp4zg6qw0u6vlu0sk8u8kqdnhwa3zjh4z46gdr8snq908e77"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1u2anh7rm26qp4zg6qw0u6vlu0sk8u8kqdnhwa3zjh4z46gdr8snq908e77"
