apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:9I31m8beJYpUm8h7zpeUYSyTnupTn1XKOUQP9QHOx2E=,iv:+CPVOSkaf2KxeRlvfnVloX6eS6yKBgjJzueGr48z9O0=,tag:FtFpwDL9KEBvuRpxqpbFzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u2anh7rm26qp4zg6qw0u6vlu0sk8u8kqdnhwa3zjh4z46gdr8snq908e77
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Mm4rcTNoSjU2MFhCSXVt
            UzU4L3pkL0VTTm9BQ0xnSXBoa0ZjZi9GcTNzCko4NWZUT1RtcmFjT290S0JiZWV4
            bDA2VzZidUxKNVhZSTJwT1ByNk1PZFUKLS0tIDlNLzBWV09zcXA4ZnFCVUtaUXE3
            N2k4aE5rdXNKOEtEQVJheWg5M2NsVXcKQeDmuavrzWOzGQzET55wVhpyuXl9J32X
            izfO0gd1oopbC/PbaLUdVbX8jGO2k14vxq8N6YKRxHmDWVVFyOSnAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-28T03:00:41Z"
    mac: ENC[AES256_GCM,data:rhSIMHH7qNFbW5IbD0NCkMVyx8OWxkZ2vOAl15MIBpZ5QAfqAXJyGaKmkFvLzipLMO3sM1+WZqYwek4cJcfrJhgc935BEcCCVfns7ca0GB/YrsmY5DqiqnJEm9tHw8BtDzfmPJDAqugbcIZ95fn2tmGyso1VuYQ9JL+vRK7T0jE=,iv:3bmhi4TufxuKB22mlmfzVbL9UlPjiuzo19lWXK4YQx8=,tag:BMMIvgMCL7nksLx9MjLkbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
